### ISSUE TITLE
Enhance post_load hook with sanity check request

### ISSUE THREAD

**Issue by jhg03a** [SolidWallOfCode/txn_box#29]
The most important thing for ATS is to successfully pass traffic.  The txnbox syntax/grammer checks are one degree of safety, but would be a significant gain if there were a way to file a test request through a pending config during post_load to determine if the new config is functionally correct.

A few thoughts tossed around in slack:
- Using a private IP space (i.e. localhost) could be used to differentiate pending versus production config
- Rather than putting the burden on txnbox to define success or failure, an external process hook could be used and the exit code fed back into txnbox
- Roll forward is going to be a lot simpler to gate than dealing with Roll back.  It avoids the idea of monitoring state after application of the new config and avoids dealing with cruft cleanup of old configs.  If rollback is needed, an external process can govern monitoring and submitting an inverse config to Roll Forward through.

**Comment by SolidWallOfCode** [comment]
My current thinking here is the the `post-load` directives should be called before the configuration is accepted, so that such directives can fail out the configuration with an error return. That doesn't address the point of being able to try out the new configuration with actual traffic, so need to keep the above points in mind.

**Comment by SolidWallOfCode** [comment]
Implmented in 0.2.12.
